{% set name = "overturemaps" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/overturemaps-{{ version }}.tar.gz
  sha256: e92355dcc2961da0ce95ab9837a59f2d15bcc357be51d0c415ceab3d812fc97d

build:
  entry_points:
    - overturemaps = overturemaps.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - click >=8.3.0
    - numpy >=1.26.4
    - orjson
    - pyarrow >=15.0.2
    - shapely >=2.1.0
    - colorama
    - pyfiglet
    - tqdm

test:
  imports:
    - overturemaps
  commands:
    - pip check
    - overturemaps --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OvertureMaps/overturemaps-py
  summary: Python tools for interacting with Overture Maps (overturemaps.org) data.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.overturemaps.org
  dev_url: https://github.com/OvertureMaps/overturemaps-py

extra:
  recipe-maintainers:
    - owenlamont
    - yu-ta-sato
